import os
import threading
import time
import uuid

_lock = threading.Lock()
_last = 0


def uuid7(ms: int | None = None) -> uuid.UUID:
    """UUIDv7 (RFC 9562): 48-bit Unix ms timestamp followed by random bits.

    Values generated by one process are strictly increasing (when ``ms`` is not given), so
    sorting by id equals creation order.
    """
    global _last  # noqa: PLW0603 - process-wide monotonic state
    timestamp = time.time_ns() // 1_000_000 if ms is None else ms
    value = (timestamp & 0xFFFF_FFFF_FFFF) << 80 | int.from_bytes(os.urandom(10), "big")
    value = (value & ~(0xF << 76)) | (0x7 << 76)  # version 7
    value = (value & ~(0x3 << 62)) | (0x2 << 62)  # RFC 4122 variant
    if ms is None:
        with _lock:
            if value <= _last:
                value = _last + 1
                # Stay valid if the +1 carried into the version/variant bits (astronomically rare).
                value = (value & ~(0xF << 76)) | (0x7 << 76)
                value = (value & ~(0x3 << 62)) | (0x2 << 62)
            _last = value
    return uuid.UUID(int=value)


def is_uuid7(value: uuid.UUID) -> bool:
    return value.version == 7 and value.variant == uuid.RFC_4122
